# Generated by Django 5.2.1 on 2026-04-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internprofile',
            name='department',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
