# Generated by Django 5.2.1 on 2026-04-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_dayschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internprofile',
            name='required_hours',
            field=models.IntegerField(default=0),
        ),
    ]
