# Generated by Django 5.2.1 on 2026-04-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('weekly', 'Weekly Report'), ('monthly', 'Monthly Report'), ('timesheet', 'Timesheet'), ('journal', 'Journal Report')], max_length=20),
        ),
    ]
