# Generated by Django 5.2.1 on 2026-04-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourlog',
            name='break_deduction',
            field=models.CharField(choices=[('none', 'No break deduction'), ('one_hour', 'Deduct 1 hour for break')], default='one_hour', max_length=20),
        ),
        migrations.AddField(
            model_name='hourlog',
            name='time_in_afternoon',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hourlog',
            name='time_out_afternoon',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
