# Generated by Django 5.2.1 on 2026-04-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging_app', '0003_hourlog_break_deduction_hourlog_time_in_afternoon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourlog',
            name='logging_mode',
            field=models.CharField(choices=[('single', 'Single Period (Auto 1-hour break deduction)'), ('split', 'Split Shift (Morning & Afternoon)')], default='split', max_length=20),
        ),
    ]
